### ISSUE TITLE
Problema complilazione del progetto su installazione di Alfresco 5.2 e moduli amp

### ISSUE THREAD

**Issue by vincenzotirelli-snap** [consiglionazionaledellericerche/cool-jconon-template#1]
Stiamo provando ad avviare l'applicativo con una installazione senza docker di Alfresco e dei relativi moduli amps, ma l'esecuzione del comando:

java -jar target/selezioni-template.war --rrd.path=remote-shared,remote-single-model --oil.url=http://localhost:9081/rest --user.admin.password=admin --server.servlet.context-path=/ --repository.base.url=http://localhost:9080/alfresco/ --spring.profiles.active=dev --spid.enable=true --spid.issuer.entityid=https://miauri.it --spid.destination=http://localhost:8080/spid/send-response

restituisce l'errore presente nel file:

[cool-jconon-template.log](https://github.com/consiglionazionaledellericerche/cool-jconon-template/files/7104003/cool-jconon-template.log)

Di seguito le versioni dei software installate sulla macchina CentOS su cui abbiamo provato le installazioni:

Apache Maven 3.0.5 (Red Hat 3.0.5-17)

Maven home: /usr/share/maven
Java version: 1.8.0_302, vendor: Red Hat, Inc.
Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.302.b08-0.el7_9.x86_64/jre
Default locale: it_IT, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-1160.36.2.el7.x86_64", arch: "amd64", family: "unix"

**Comment by mspasiano** [comment]
Accedendo alla URL: http://localhost:9080/alfresco/s/admin/admin-repoconsole ed eseguendo il comando "show models" dovreste verificare che il modello "jconon_competition_folder.xml" sia presente e sia attivo, nel caso in cui sia presente ma non attivo dovreste attivarlo con il comando "activate model jconon_competition_folder.xml"

**Comment by vincenzotirelli-snap** [comment]
L'esecuzione del comando "show models" non restituisce nessun risultato e viene mostrato il messaggio "No additional models have been deployed to the Alfresco Repository"

**Comment by mspasiano** [comment]
Accedendo alla seguente URL: http://localhost:9080/alfresco/webdav/Data%20Dictionary/Models dovrebbero esserci i file xml dei modelli, dal file di log si ev

**Comment by mspasiano** [comment]
Accedendo alla segente URL: http://localhost:9080/alfresco/webdav/Data%20Dictionary/Models dovrebbero esserci i file xml di definizione dei modelli, dal file di log si evince che sono presenti.

**Comment by vincenzotirelli-snap** [comment]
I file xml di definizione dei modelli jconon sono presenti, compreso il jconon_competition_folder.xml.
Qui trovi l'elenco di tutti i modelli visualizzati:
[modelli_presenti.txt](https://github.com/consiglionazionaledellericerche/cool-jconon-template/files/7104586/modelli_presenti.txt)

**Comment by mspasiano** [comment]
Dovresti verificare che il tipo del file xml sia "cm:dictionaryModel" come da schermata allegata, in caso affermativo c'è qualche problema nell'installazione di Alfresco, altrimenti vuol dire che i file dei modelli sono stati copiati in altro modo.
![Schermata del 2021-09-03 11-37-21](https://user-images.githu busercontent.com/8926256/131984893-1f142735-9361-4e09-ad46-622d415aa313.png)

**Comment by vincenzotirelli-snap** [comment]
Il nodo riportato cm:jconon_competition_folder.xml non è presente nella nostra installazione. 
![Image 1](https://user-images.githubusercontent.com/90028275/131987309-a6f4d851-427f-429d-8418-0b1abd03d21b.png)
Ad ogni modo, dopo aver installato Alfresco e cambiato le porte del tomcat, ci siamo limitati ad installare i tre moduli amp indicati nella guida utilizzando il comando apply_amps.sh. 
Forse abbiamo mancato qualche passaggio nell'installazione dei moduli aggiuntivi?

**Comment by mspasiano** [comment]
Da quello che vedo sembra che l'installazione di Alfresco sia in Italiano,  invece deve essere in inglese.

**Comment by vincenzotirelli-snap** [comment]
La reinstallazione di Alfresco in lingua inglese e dei relativi plugin non è stata risolutiva.
Continuiamo a non vedere i modelli indicati nell'interfaccia di amministrazione di Alfresco e, di conseguenza la compilazione ed il primo avvio del template va in errore.
La versione di Alfresco che abbiamo installato è quella presente al seguente link:

https://download.alfresco.com/release/community/201707-build-00028/alfresco-community-installer-201707-linux-x64.bin

Abbiamo, inoltre, provato nuovamente ad installare cool-jconon-template tramite docker ma provando ad accedere all'indirizzo http://10.10.1.15:9080/ viene mostrato il seguente errore

![Image 3](https://user-images.githubusercontent.com/90028275/132042410-b6aac128-0e45-4f99-9ff9-b72d77200efe.jpg)

**Comment by mspasiano** [comment]
L'installazione di Alfresco deve creare le cartelle di inizializzazione in inglese e non in italiano, se l'installazione è fatta con il bundle indicato basta aggiungere nel file scripts/setenv.sh la seguente variabile di ambiente:

LANG=en_US.UTF-8
export LANG

**Comment by vincenzotirelli-snap** [comment]
La modifica della lingua ci ha permesso di vedere i modelli e di avviare il progetto per le personalizzazioni della piattaforma.
Grazie mille per il supporto, procedo alla chiusura dell'issue.
