### ISSUE TITLE
Errore in fase di caricamento allegato pdf troppo pesante

### ISSUE THREAD

**Issue by GiovanniScieri** [consiglionazionaledellericerche/cool-jconon-template#10]
In fase di caricamento di un allegato pdf, qualora questo fosse troppo pesante, viene restituito correttamente l'errore ma successivamente compare una riga che riporta il pdf, apparentemente caricato, ma con dimensione 0 bytes.
![errore pdf](https://user-images.githubusercontent.com/16743503/217028206-6c4c0ed5-73bb-41c3-b51f-341aa24cf2cf.jpg)

**Comment by mspasiano** [comment]
Risolta con la versione 5.0.36 di cool-jconon
