### ISSUE TITLE
Accesso SPID ErrorCode nr5

### ISSUE THREAD

**Issue by vincenzotirelli-snap** [consiglionazionaledellericerche/cool-jconon-template#3]
Abbiamo attivato l'accesso SPID dell'applicativo utilizzando un unico metadata in comune ad altri applicativi già in esercizio.
Il metadata, integrato con gli elementi specifici dell'installazione jconon, è stato inviato, validato e traferito  da AGID agli Identity Provider.
Provando ad accedere ad qualunque provider riceviamo il messaggio:

Namirial.ID - Impossibile stabilire l'autenticità della richiesta. ErrorCode nr05

Per configurare dell'accesso tramite SPID abbiamo aggiunto i seguenti parametri all'avvio dell'applicazione:

--spid.enable=true \
--spid.issuer.entityid=https://web.comune.benevento.it \
--spid.keystore.path=classpath:keystore/certificato.pkcs12 \
--spid.keystore.password={pwd} \
--spid.attributeConsumingServiceIndex=2 \
--spid.assertionConsumerServiceIndex=1 \

Di seguito l'indirizzo del servizio e le versioni dei software installate sulla macchina CentOS su cui abbiamo è installato l'applicativo:

https://selezioni.comune.benevento.it/

Apache Maven 3.0.5 (Red Hat 3.0.5-17)

Maven home: /usr/share/maven
Java version: 1.8.0_302, vendor: Red Hat, Inc.
Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.302.b08-0.el7_9.x86_64/jre
Default locale: it_IT, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-1160.36.2.el7.x86_64", arch: "amd64", family: "unix"

Cordiali saluti

**Comment by mspasiano** [comment]
Ciao, guarda a me sembra tutto corretto, infatti ho provato con InfoCert e funziona
