### ISSUE TITLE
Error error Internal Server Error

### ISSUE THREAD

**Issue by GiovannaTes** [consiglionazionaledellericerche/cool-jconon-template#4]
Dopo un po' di tempo che l'applicativo ha funzionato, improvvisamente senza nessun operazione apparente ha iniziato a dare il seguente errore 

{"error":"10240065 Request failed 500 /solr4/alfresco/cmis?wt=json&fl=DBID%2Cscore&rows=10&df=TEXT&start=0&locale=en_US&alternativeDic=DEFAULT_DICTIONARY&cmisVersion=CMIS_1_1&fq=%7B%21afts%7DAUTHORITY_FILTER_FROM_JSON&fq=%7B%21afts%7DTENANT_FILTER_FROM_JSON"}

cool-jconon version 4.9.17

**Comment by mspasiano** [comment]
Salve,
Se può controllare cosa è successo nei log di Alfresco, in linea di massima potrebbe essere un problema di spazio o di occupazione di memoria.

**Comment by GiovannaTes** [comment]
Salve,
ho controllato lo spazio su disco è sufficiente, nei log di Alfresco non ci sono particolari indicazioni, per il momento ho risolto rispristinando il backup del giorno prima.
